import { formatIqd, loadLocalData, saveLocalData, today, totals, uid } from "./data.js";
import { saveCloudData, startFirebase } from "./firebase-service.js";
import { printInvoice, shareInvoice } from "./print-service.js";
import { dashboard, managePage, navItems, ordersPage, reportsPage, settingsPage } from "./ui.js";

let data = loadLocalData(); let page = "today"; let orderFilter = "all"; let sync = "connecting"; let firebaseReady = false;
const root = document.querySelector("#page-root"), nav = document.querySelector("#main-nav"), title = document.querySelector("#page-title"), kicker = document.querySelector("#page-kicker"), dialog = document.querySelector("#order-dialog"), form = document.querySelector("#order-form");

function toast(message, error=false){const item=document.createElement("div");item.className=`toast${error?" error":""}`;item.textContent=message;document.querySelector("#toast-region").append(item);setTimeout(()=>item.remove(),3600);}
function setSync(next){sync=next;const card=document.querySelector("#sync-card"),copy=document.querySelector("#sync-copy");card.className=`sync-card ${next}`;copy.textContent=next==="synced"?"Firebase متصل ومُزامن":next==="denied"?"تم رفض الوصول؛ راجع قواعد Firebase":next==="timeout"?"تعذر الرد؛ تحقق من الشبكة أو القواعد":next==="offline"?"تعذر الاتصال؛ تستخدم نسخة محلية":"جارِ الاتصال بـ Firebase";render();}
function persist(){saveLocalData(data);if(firebaseReady)saveCloudData(data).then(()=>setSync("synced")).catch(()=>setSync("offline"));}
function renderNav(){nav.innerHTML=navItems.map(item=>`<button class="nav-button ${item.id===page?"active":""}" data-page="${item.id}"><span class="nav-icon">${item.icon}</span>${item.label}</button>`).join("");}
function render(){renderNav();const info={today:["لوحة المتابعة","صباح الخير"],orders:["المبيعات والتوصيل","الطلبات"],reports:["تحليل الأداء","التقارير"],manage:["البيانات الأساسية","الإدارة"],settings:["التفضيلات والبيانات","الإعدادات"]}[page];kicker.textContent=info[0];title.textContent=info[1];root.innerHTML=page==="today"?dashboard(data):page==="orders"?ordersPage(data,orderFilter):page==="reports"?reportsPage(data):page==="manage"?managePage(data):settingsPage(sync);}
function populateOrderForm(){document.querySelector("#order-shop").innerHTML=data.shops.map(s=>`<option value="${s.id}">${s.name}</option>`).join("");document.querySelector("#order-rep").innerHTML=`<option value="">غير محدد</option>${data.representatives.map(r=>`<option value="${r.id}">${r.name}</option>`).join("")}`;document.querySelector("#order-product").innerHTML=data.products.map(p=>`<option value="${p.id}">${p.icon} ${p.name} — ${formatIqd(p.price)}</option>`).join("");document.querySelector("#order-date").value=today();updatePreview();}
function updatePreview(){const product=data.products.find(p=>p.id===document.querySelector("#order-product").value);const quantity=Number(document.querySelector("#order-quantity").value||0);document.querySelector("#order-preview").textContent=formatIqd((product?.price||0)*quantity);}
function openOrder(){if(!data.shops.length||!data.products.length)return toast("أضف محلاً ومنتجاً أولاً من صفحة الإدارة.",true);populateOrderForm();dialog.showModal();}
function addOrder(){const shop=data.shops.find(s=>s.id===document.querySelector("#order-shop").value);const representative=data.representatives.find(r=>r.id===document.querySelector("#order-rep").value);const product=data.products.find(p=>p.id===document.querySelector("#order-product").value);const quantity=Number(document.querySelector("#order-quantity").value);if(!shop||!product||!quantity)return toast("أكمل بيانات الطلب بصورة صحيحة.",true);const item={id:uid("item"),category:product.category,name:product.name,icon:product.icon,quantity,sellPrice:product.price,costPrice:product.cost,unitLabel:"قطعة",revenue:product.price*quantity,cost:product.cost*quantity,profit:(product.price-product.cost)*quantity};const sum=totals([item]);data.orders.unshift({id:uid("order"),shopId:shop.id,shopName:shop.name,representativeId:representative?.id,representativeName:representative?.name||"غير محدد",date:document.querySelector("#order-date").value,createdAt:new Date().toISOString(),notes:document.querySelector("#order-notes").value.trim(),status:"pending",items:[item],totalRevenue:sum.revenue,totalCost:sum.cost,totalProfit:sum.revenue-sum.cost});persist();dialog.close();toast("تم حفظ الطلب ومزامنته عند توفر الاتصال.");render();}
function promptAdd(kind){const labels={shop:"اسم المحل",rep:"اسم المندوب",product:"اسم المنتج"};const name=prompt(labels[kind]);if(!name?.trim())return;if(kind==="shop")data.shops.push({id:uid("shop"),name:name.trim(),area:"",phone:"",owner:"",location:""});if(kind==="rep")data.representatives.push({id:uid("rep"),name:name.trim(),area:"",phone:""});if(kind==="product"){const price=Number(prompt("سعر البيع بالدينار", "4000"));const cost=Number(prompt("سعر التكلفة بالدينار", "3250"));if(!Number.isFinite(price)||!Number.isFinite(cost))return toast("أدخل أسعاراً صحيحة.",true);data.products.push({id:uid("product"),name:name.trim(),category:"other",icon:"📦",price,cost});}persist();toast("تمت الإضافة.");render();}
async function printById(id,share=false){const order=data.orders.find(o=>o.id===id);if(!order)return toast("لا يوجد طلب للطباعة.",true);try{if(share)await shareInvoice(order);else printInvoice(order);}catch(error){toast(error.message||"تعذرت العملية.",true);}}
document.addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;if(button.dataset.page){page=button.dataset.page;document.querySelector(".sidebar").classList.remove("open");render();}if(button.dataset.filter){orderFilter=button.dataset.filter;render();}if(button.dataset.action==="new-order")openOrder();if(button.dataset.action==="print")printById(button.dataset.id);if(button.dataset.action==="print-last")printById(data.orders[0]?.id);if(button.dataset.action==="add-shop")promptAdd("shop");if(button.dataset.action==="add-rep")promptAdd("rep");if(button.dataset.action==="add-product")promptAdd("product");if(button.id==="print-quick")printById(data.orders[0]?.id);if(button.id==="menu-toggle")document.querySelector(".sidebar").classList.toggle("open");});
form.addEventListener("submit",event=>{event.preventDefault();addOrder();});document.querySelector("#order-product").addEventListener("change",updatePreview);document.querySelector("#order-quantity").addEventListener("input",updatePreview);
startFirebase({fallback:()=>data,onData:(remote)=>{if(remote?.shops&&remote?.products&&remote?.orders){data=remote;saveLocalData(data);render();}},onStatus:(next)=>{firebaseReady=next==="synced";setSync(next);}});render();
