import { formatIqd, statusLabel } from "./data.js";

export const navItems = [{ id: "today", icon: "⌂", label: "اليوم" }, { id: "orders", icon: "☷", label: "الطلبات" }, { id: "reports", icon: "▥", label: "التقارير" }, { id: "manage", icon: "▣", label: "الإدارة" }, { id: "settings", icon: "⚙", label: "الإعدادات" }];
export function empty(title, detail) { return `<div class="empty"><span class="empty-icon">▧</span><strong>${title}</strong><span>${detail}</span></div>`; }
export function status(status) { return `<span class="status ${status}">${statusLabel(status)}</span>`; }
export function dashboard(data) {
  const day = new Date().toISOString().slice(0, 10); const todayOrders = data.orders.filter((order) => order.date === day && order.status !== "returned"); const revenue = todayOrders.reduce((sum, order) => sum + order.totalRevenue, 0); const profit = todayOrders.reduce((sum, order) => sum + order.totalProfit, 0); const pending = data.orders.filter((order) => order.status === "pending").length;
  return `<section class="hero"><div><p class="eyebrow">خطة اليوم</p><h2>كل طلباتك في مكان واحد</h2><p>أضف الطلب، تابع التسليم، وراجع الربح مباشرة.</p></div><div class="hero-icon">▣</div></section><section class="metric-grid"><article class="metric dark"><small>طلبات اليوم</small><strong>${todayOrders.length}</strong></article><article class="metric orange"><small>إيراد اليوم</small><strong>${formatIqd(revenue)}</strong></article><article class="metric green"><small>ربح اليوم</small><strong>${formatIqd(profit)}</strong></article><article class="metric red"><small>بانتظار التوصيل</small><strong>${pending}</strong></article></section><div class="toolbar"><div><h3>أحدث الطلبات</h3><p class="subcopy">آخر العمليات المسجلة في النظام</p></div><button class="button button-primary" data-action="new-order">＋ إضافة طلب</button></div><section class="section-card orders">${ordersTable(data.orders.slice(0,5))}</section>`;
}
export function ordersTable(orders) { if (!orders.length) return empty("لا توجد طلبات بعد", "أضف أول طلب لتبدأ متابعة التوزيع والأرباح."); return `<table class="data-table"><thead><tr><th>المحل</th><th>التاريخ</th><th>المندوب</th><th>الإجمالي</th><th>الحالة</th><th></th></tr></thead><tbody>${orders.map((order) => `<tr><td>${order.shopName}</td><td>${order.date}</td><td>${order.representativeName}</td><td>${formatIqd(order.totalRevenue)}</td><td>${status(order.status)}</td><td><button class="button button-secondary" data-action="print" data-id="${order.id}">طباعة</button></td></tr>`).join("")}</tbody></table>`; }
export function ordersPage(data, activeFilter) { const visible = activeFilter === "all" ? data.orders : data.orders.filter((order) => order.status === activeFilter); return `<section class="list-page"><div class="page-header"><div><p class="eyebrow">المبيعات والتوصيل</p><h2>الطلبات</h2><p>ابحث في الطلبات، ثم اطبع فاتورة أي عملية فوراً.</p></div><button class="button button-primary" data-action="new-order">＋ طلب جديد</button></div><div class="filter-row">${["all","pending","delivered","returned"].map((filter) => `<button class="filter ${activeFilter===filter?"active":""}" data-filter="${filter}">${filter === "all" ? "الكل" : statusLabel(filter)}</button>`).join("")}</div><section class="section-card orders">${ordersTable(visible)}</section></section>`; }
export function reportsPage(data) { const delivered = data.orders.filter((order)=>order.status === "delivered"); const revenue = delivered.reduce((sum,order)=>sum+order.totalRevenue,0); const profit = delivered.reduce((sum,order)=>sum+order.totalProfit,0); const byShop = Object.values(delivered.reduce((map,order)=>{map[order.shopName]=(map[order.shopName]||0)+order.totalRevenue;return map;},{})).sort((a,b)=>b-a); const max = byShop[0] || 1; return `<section class="list-page"><div class="page-header"><div><p class="eyebrow">تحليل الأداء</p><h2>التقارير</h2><p>تُحتسب الأرقام من الطلبات المستلمة فقط.</p></div></div><div class="metric-grid"><article class="metric dark"><small>إجمالي مستلم</small><strong>${delivered.length}</strong></article><article class="metric orange"><small>إيراد مستلم</small><strong>${formatIqd(revenue)}</strong></article><article class="metric green"><small>ربح مستلم</small><strong>${formatIqd(profit)}</strong></article><article class="metric red"><small>طلبات راجعة</small><strong>${data.orders.filter(o=>o.status==="returned").length}</strong></article></div><div class="report-grid"><section class="section-card report-stat"><h3>الأداء حسب المحلات</h3>${byShop.length ? byShop.map((value,index)=>`<div class="bar-row"><span>محل ${index+1}</span><div class="bar"><i style="width:${Math.max(12, value/max*100)}%"></i></div><b>${formatIqd(value)}</b></div>`).join("") : empty("لا توجد بيانات مستلمة", "حوّل طلباً إلى مستلم لإظهار تقريره.")}</section><section class="section-card report-stat"><h3>احتياجات الشراء</h3>${purchaseNeeds(data)}</section></div></section>`; }
function purchaseNeeds(data){const map={};data.orders.filter(o=>o.status!=="returned").forEach(o=>o.items.forEach(i=>map[i.name]=(map[i.name]||0)+i.quantity));const entries=Object.entries(map);return entries.length?entries.map(([name,q])=>`<div class="bar-row"><span>${name}</span><div class="bar"><i style="width:70%"></i></div><b>${q}</b></div>`).join(""):empty("لا توجد احتياجات", "سوف تظهر الكميات بعد تسجيل الطلبات.");}
export function managePage(data){return `<section class="list-page"><div class="page-header"><div><p class="eyebrow">البيانات الأساسية</p><h2>الإدارة</h2><p>أضف البيانات من خلال الإجراءات السريعة أدناه.</p></div></div><div class="manage-grid"><article class="section-card manage-card"><div class="manage-count">${data.shops.length}</div><h3>المحلات</h3><p>المحلات المتاحة عند تسجيل طلب جديد.</p><button class="button button-secondary" data-action="add-shop">إضافة محل</button></article><article class="section-card manage-card"><div class="manage-count">${data.representatives.length}</div><h3>المندوبون</h3><p>أفراد فريق التوصيل والمبيعات.</p><button class="button button-secondary" data-action="add-rep">إضافة مندوب</button></article><article class="section-card manage-card"><div class="manage-count">${data.products.length}</div><h3>المنتجات</h3><p>الأسعار والتكلفة المستخدمة في الحساب.</p><button class="button button-secondary" data-action="add-product">إضافة منتج</button></article></div></section>`;}
export function settingsPage(sync){const copy=sync==="synced"?"متصل ومُزامن مع Firebase":sync==="connecting"?"جارِ الاتصال بقاعدة Firebase":sync==="denied"?"تم رفض الوصول؛ فعّل المصادقة أو راجع قواعد Firebase":sync==="timeout"?"لم تستجب القاعدة خلال 10 ثوانٍ؛ تحقق من الشبكة والقواعد":sync==="offline"?"تعذر الاتصال؛ تُحفظ نسخة محلية":"حفظ محلي";const label=sync==="synced"?"نشط":sync==="denied"?"صلاحيات":sync==="timeout"?"مهلة":"تحقق";return `<section class="list-page"><div class="page-header"><div><p class="eyebrow">التفضيلات والبيانات</p><h2>الإعدادات</h2><p>تظهر حالة مزامنة البيانات الحالية هنا.</p></div></div><section class="section-card settings-list"><div class="setting-row"><div><h3>مزامنة Firebase</h3><p>${copy}</p></div><span class="status ${sync==="synced"?"delivered":"pending"}">${label}</span></div><div class="setting-row"><div><h3>الطباعة والمشاركة</h3><p>فاتورة مهيأة للطباعة بحجم خط أساسي 14px. افتح الطلب ثم اختر طباعة.</p></div><button class="button button-secondary" data-action="print-last">طباعة آخر طلب</button></div></section></section>`;}
